/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AchDebitResponse, achDebitResponseSchema } from './achDebitResponse';
import {
  SepaDebitResponse,
  sepaDebitResponseSchema,
} from './sepaDebitResponse';

/** Full representation of a Bank Payment Token. */
export interface BankPaymentToken {
  /** A Resource representing a response of vaulted a ACH Debit Account. */
  achDebit?: AchDebitResponse;
  sepaDebit?: SepaDebitResponse;
}

export const bankPaymentTokenSchema: Schema<BankPaymentToken> = object({
  achDebit: ['ach_debit', optional(lazy(() => achDebitResponseSchema))],
  sepaDebit: ['sepa_debit', optional(lazy(() => sepaDebitResponseSchema))],
});
