/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InstrumentAuthorizationStatus
 */
export enum InstrumentAuthorizationStatus {
  Authorized = 'AUTHORIZED',
  Blocked = 'BLOCKED',
  Failed = 'FAILED',
  NotApplicable = 'NOT_APPLICABLE',
  NotSupported = 'NOT_SUPPORTED',
  Unauthorized = 'UNAUTHORIZED',
}

/**
 * Schema for InstrumentAuthorizationStatus
 */
export const instrumentAuthorizationStatusSchema: Schema<InstrumentAuthorizationStatus> = stringEnum(
  InstrumentAuthorizationStatus,
  true
);
