/**
 * PayPal REST APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InstrumentAuthorizationStatus,
  instrumentAuthorizationStatusSchema,
} from './instrumentAuthorizationStatus';

/** Authorization details. */
export interface SepaDebitAuthorizationDetails {
  /** The authorization status of the wallet instrument. */
  status?: InstrumentAuthorizationStatus;
}

export const sepaDebitAuthorizationDetailsSchema: Schema<SepaDebitAuthorizationDetails> = object(
  { status: ['status', optional(instrumentAuthorizationStatusSchema)] }
);
